FROM docker.io/library/mono:latest

RUN apt-get update && apt-get install -y git

VOLUME /data

COPY entrypoint.sh /entrypoint.sh
COPY tools.txt /tools.txt

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
